### ISSUE TITLE
Error when i run.

### ISSUE THREAD

**Issue by mrtortong** [lucapiccinelli/BarcodesTutorial#1]
Traceback (most recent call last):
  File "barcodeTutorial.py", line 9, in <module>
    scale = 800.0 / im.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by lucapiccinelli** [comment]
Seems like your im object is not initialized. The only instructions that you are executing are those of the tutorial? im is initialized with "im = cv2.imread(r'img\barcodes.jpg', cv2.IMREAD_GRAYSCALE)" and no other instructions act on it in the tutorial code... so maybe you should first ensure that your opencv is correctly loaded and that is able to load images from disk.
